// utils/nationalities.js
module.exports = [
  { en: "Egyptian", ar: "مصري" },
  { en: "Emirati", ar: "إماراتي" },
  { en: "Saudi", ar: "سعودي" },
  { en: "Jordanian", ar: "أردني" },
  { en: "Syrian", ar: "سوري" },
  { en: "Indian", ar: "هندي" },
  { en: "Pakistani", ar: "باكستاني" },
  { en: "Filipino", ar: "فلبيني" },
  { en: "Sudanese", ar: "سوداني" },
  { en: "Lebanese", ar: "لبناني" },
  { en: "Iraqi", ar: "عراقي" },
  { en: "Tunisian", ar: "تونسي" },
  { en: "Algerian", ar: "جزائري" },
  { en: "Moroccan", ar: "مغربي" },
  { en: "Omani", ar: "عماني" },
  { en: "Qatari", ar: "قطري" },
  { en: "Kuwaiti", ar: "كويتي" },
  { en: "Bahraini", ar: "بحريني" },
  { en: "Yemeni", ar: "يمني" },
  { en: "Libyan", ar: "ليبي" },
  { en: "Palestinian", ar: "فلسطيني" },
  { en: "Somali", ar: "صومالي" },
  { en: "Mauritanian", ar: "موريتاني" },
  { en: "Comorian", ar: "قمري" },
  { en: "Djiboutian", ar: "جيبوتي" },
  { en: "Eritrean", ar: "إريتري" },
  { en: "Ethiopian", ar: "إثيوبي" },
  { en: "Bangladeshi", ar: "بنغلاديشي" },
  { en: "Sri Lankan", ar: "سريلانكي" },
  { en: "Nepali", ar: "نيبالي" },
  { en: "Chinese", ar: "صيني" },
  { en: "Japanese", ar: "ياباني" },
  { en: "Korean", ar: "كوري" },
  { en: "Malaysian", ar: "ماليزي" },
  { en: "Indonesian", ar: "إندونيسي" },
  { en: "Thai", ar: "تايلاندي" },
  { en: "Vietnamese", ar: "فيتنامي" },
  { en: "Iranian", ar: "إيراني" },
  { en: "Turkish", ar: "تركي" },
  { en: "Russian", ar: "روسي" },
  { en: "German", ar: "ألماني" },
  { en: "French", ar: "فرنسي" },
  { en: "British", ar: "بريطاني" },
  { en: "American", ar: "أمريكي" },
  { en: "Canadian", ar: "كندي" },
  { en: "Australian", ar: "أسترالي" },
  { en: "New Zealander", ar: "نيوزيلندي" },
  { en: "South African", ar: "جنوب أفريقي" },
  { en: "Brazilian", ar: "برازيلي" },
  { en: "Mexican", ar: "مكسيكي" },
  { en: "Argentinian", ar: "أرجنتيني" },
  { en: "Spanish", ar: "إسباني" },
  { en: "Italian", ar: "إيطالي" },
  { en: "Greek", ar: "يوناني" },
  { en: "Swedish", ar: "سويدي" },
  { en: "Norwegian", ar: "نرويجي" },
  { en: "Danish", ar: "دنماركي" },
  { en: "Finnish", ar: "فنلندي" },
  { en: "Dutch", ar: "هولندي" },
  { en: "Belgian", ar: "بلجيكي" },
  { en: "Swiss", ar: "سويسري" },
  { en: "Austrian", ar: "نمساوي" },
  { en: "Portuguese", ar: "برتغالي" },
  { en: "Irish", ar: "إيرلندي" },
  { en: "Scottish", ar: "اسكتلندي" },
  { en: "Welsh", ar: "ويلزي" },
  { en: "Ukrainian", ar: "أوكراني" },
  { en: "Polish", ar: "بولندي" },
  { en: "Romanian", ar: "روماني" },
  { en: "Hungarian", ar: "مجري" },
  { en: "Czech", ar: "تشيكي" },
  { en: "Slovak", ar: "سلوفاكي" },
  { en: "Bulgarian", ar: "بلغاري" },
  { en: "Serbian", ar: "صربي" },
  { en: "Croatian", ar: "كرواتي" },
  { en: "Bosnian", ar: "بوسني" },
  { en: "Albanian", ar: "ألباني" },
  { en: "Kosovan", ar: "كوسوفي" },
  { en: "Macedonian", ar: "مقدوني" },
  { en: "Slovenian", ar: "سلوفيني" },
  { en: "Lithuanian", ar: "ليتواني" },
  { en: "Latvian", ar: "لاتفي" },
  { en: "Estonian", ar: "إستوني" },
  { en: "Icelandic", ar: "آيسلندي" },
  { en: "Maltese", ar: "مالطي" },
  { en: "Cypriot", ar: "قبرصي" },
  { en: "Georgian", ar: "جورجي" },
  { en: "Armenian", ar: "أرميني" },
  { en: "Azerbaijani", ar: "أذربيجاني" },
  { en: "Kazakh", ar: "كازاخستاني" },
  { en: "Uzbek", ar: "أوزبكي" },
  { en: "Turkmen", ar: "تركمانستاني" },
  { en: "Kyrgyz", ar: "قيرغيزي" },
  { en: "Tajik", ar: "طاجيكي" },
  { en: "Afghan", ar: "أفغاني" },
  { en: "Maldivian", ar: "مالديفي" },
  { en: "Singaporean", ar: "سنغافوري" },
  { en: "Bruneian", ar: "بروني" },
  { en: "Fijian", ar: "فيجي" },
  { en: "Papua New Guinean", ar: "بابوا غيني جديد" },
  { en: "Solomon Islander", ar: "من جزر سليمان" },
  { en: "Vanuatuan", ar: "فانواتي" },
  { en: "Samoan", ar: "ساموي" },
  { en: "Tongan", ar: "تونغي" },
  { en: "Kiribati", ar: "كيريباتي" },
  { en: "Marshallese", ar: "مارشالي" },
  { en: "Micronesian", ar: "ميكرونيزي" },
  { en: "Nauruan", ar: "ناورو" },
  { en: "Palauan", ar: "بالاوي" },
  { en: "Tuvaluan", ar: "توفالوي" },
  { en: "Andorran", ar: "أندوري" },
  { en: "San Marinese", ar: "من سان مارينو" },
  { en: "Monegasque", ar: "موناكي" },
  { en: "Vatican", ar: "فاتيكاني" },
  { en: "Greenlandic", ar: "جرينلاندي" },
  { en: "Faroese", ar: "فاروي" },
  { en: "Guernseyan", ar: "جيرنزي" },
  { en: "Jersey", ar: "جيرسي" },
  { en: "Manx", ar: "مانكسي" },
  { en: "Gibraltarian", ar: "جبل طارقي" },
  { en: "Caymanian", ar: "من جزر كايمان" },
  { en: "Bermudian", ar: "برمودي" },
  { en: "Bahamian", ar: "باهامي" },
  { en: "Barbadian", ar: "بربادوسي" },
  { en: "Jamaican", ar: "جامايكي" },
  { en: "Trinidadian", ar: "ترينيدادي" },
  { en: "Haitian", ar: "هايتي" },
  { en: "Dominican", ar: "دومينيكي" },
  { en: "Cuban", ar: "كوبي" },
  { en: "Puerto Rican", ar: "بورتوريكي" },
  { en: "Guatemalan", ar: "غواتيمالي" },
  { en: "Honduran", ar: "هندوراسي" },
  { en: "Salvadoran", ar: "سلفادوري" },
  { en: "Nicaraguan", ar: "نيكاراغوي" },
  { en: "Costa Rican", ar: "كوستاريكي" },
  { en: "Panamanian", ar: "بنماوي" },
  { en: "Colombian", ar: "كولومبي" },
  { en: "Venezuelan", ar: "فنزويلي" },
  { en: "Ecuadorian", ar: "إكوادوري" },
  { en: "Peruvian", ar: "بيروفي" },
  { en: "Bolivian", ar: "بوليفي" },
  { en: "Chilean", ar: "تشيلي" },
  { en: "Uruguayan", ar: "أوروغواياني" },
  { en: "Paraguayan", ar: "باراغواياني" },
  { en: "Guyanese", ar: "غياني" },
  { en: "Surinamese", ar: "سورينامي" },
  { en: "French Guianan", ar: "غياني فرنسي" },
  { en: "Belizean", ar: "بليزي" },
  { en: "Antiguan", ar: "أنتيجوي" },
  { en: "Vincentian", ar: "فنسنت و غرينادين" },
  { en: "Grenadian", ar: "غرينادي" },
  { en: "Saint Lucian", ar: "سانت لوسياني" },
  { en: "Kittitian", ar: "كيتياني" },
  { en: "Dominican (Commonwealth)", ar: "دومينيكي (كومنولث)" },
  { en: "Bajan", ar: "باجاني" }, // Another term for Barbadian
  { en: "Aruban", ar: "أروبي" },
  { en: "Curaçaoan", ar: "كوراساوي" },
  { en: "Sint Maarten", ar: "سينت مارتن" },
  { en: "Bonairean", ar: "بونيري" },
  { en: "Saban", ar: "ساباني" },
  { en: "Statian", ar: "ستاتياني" },
  { en: "Gambian", ar: "غامبي" },
  { en: "Senegalese", ar: "سنغالي" },
  { en: "Guinean", ar: "غيني" },
  { en: "Guinean-Bissau", ar: "غيني بيساوي" },
  { en: "Sierra Leonean", ar: "سيراليوني" },
  { en: "Liberian", ar: "ليبيري" },
  { en: "Ivorian", ar: "إيفواري" },
  { en: "Ghanaian", ar: "غاني" },
  { en: "Togolese", ar: "توغولي" },
  { en: "Beninese", ar: "بنيني" },
  { en: "Nigerian", ar: "نيجيري" },
  { en: "Nigerien", ar: "نيجري" },
  { en: "Burkinabé", ar: "بوركيني" },
  { en: "Malian", ar: "مالي" },
  { en: "Chadian", ar: "تشادي" },
  { en: "Central African", ar: "أفريقي وسطي" },
  { en: "Cameroonian", ar: "كاميروني" },
  { en: "Gabonese", ar: "غابوني" },
  { en: "Congolese (Brazzaville)", ar: "كونغولي (برازافيل)" },
  { en: "Congolese (DRC)", ar: "كونغولي (جمهورية الكونغو الديمقراطية)" },
  { en: "Angolan", ar: "أنغولي" },
  { en: "Zambian", ar: "زامبي" },
  { en: "Zimbabwean", ar: "زيمبابوي" },
  { en: "Malawian", ar: "مالاوي" },
  { en: "Mozambican", ar: "موزمبيقي" },
  { en: "Botswanan", ar: "بوتسواني" },
  { en: "Namibian", ar: "ناميبي" },
  { en: "Lesotho", ar: "ليسوتو" },
  { en: "Swazi", ar: "سوازي" },
  { en: "Madagascan", ar: "مدغشقري" },
  { en: "Mauritian", ar: "موريشيوسي" },
  { en: "Seychellois", ar: "سيشلي" },
  { en: "Tanzanian", ar: "تنزاني" },
  { en: "Kenyan", ar: "كيني" },
  { en: "Ugandan", ar: "أوغندي" },
  { en: "Rwandan", ar: "رواندي" },
  { en: "Burundian", ar: "بوروندي" },
  { en: "South Sudanese", ar: "جنوب سوداني" }
];